### ISSUE TITLE
Add new block for DGMM history 

### ISSUE THREAD

**Issue by kerautret** [TC-18/tc18.org#60]
It could be nice to add a block like previous edition, including best paper price ?

**Comment by kerautret** [comment]
@PerretB let me know if you want that I assign me and/or ping me when it is done I will make an announce on twitter.

**Comment by PerretB** [comment]
You are right; there is some general presentation text to modify also. I will try to do a first draft this week : would be great if you can review it

**Comment by kerautret** [comment]
yes of-course ;)
